version: '3'
services:
  xzg-mall-mysql:
    build:
      context: ./
      dockerfile: ./db/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    container_name: xzg-mall-mysql
    image: xzg-mall-mysql
    ports:
      - 3306:3306
    volumes:
      - ./xzg-mall-mysql:/var/lib/mysql
    command: --lower_case_table_names=1

  xzg-mall-redis:
    image: redis:5.0.4
    restart: always
    container_name: xzg-mall-redis
    ports:
      - 6379:6379

  xzg-mall-admin:
    build:
      context: ./
      dockerfile: ./xzg-mall-admin/Dockerfile
    restart: always
    container_name: xzg-mall-admin
    image: xzg-mall-admin
    ports:
      - 8085:8085
    depends_on:
      - xzg-mall-redis
      - xzg-mall-mysql
    links:
      - "xzg-mall-redis"
      - "xzg-mall-mysql"

  xzg-mall-api:
    build:
      context: ./
      dockerfile: ./xzg-mall-api/Dockerfile
    restart: always
    container_name: xzg-mall-api
    image: xzg-mall-api
    ports:
      - 8086:8086
    depends_on:
      - xzg-mall-redis
      - xzg-mall-mysql
    links:
      - "xzg-mall-redis"
      - "xzg-mall-mysql"